### ISSUE TITLE
Percentage GPU memory usage

### ISSUE THREAD

**Issue by acivit** [Taeert/insightface#1]
Hello!

I noticed that when I use the CUDA version of the code, the memory usage destinated for the process is always the same (a small percentage of the GPU, between 25 - 30 %), is there a way to increase it? 

Thanks!

Aniol

**Comment by tae898** [comment]
Hi Aniol,

AFAIK, mxnet will only allocate the memory that it only needs. 
Why do you want to increase the memory usage? It won't increase the performance.

**Comment by acivit** [comment]
I thought it would increase the performance, thanks for your attention! :)
